# fly.toml file generated for bloglist2023 on 2023-01-05T12:18:58+01:00

app = "bloglist2023"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 5000
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
interval = 10000
grace_period = "5s"
method = "get"
path = "/health"
protocol = "http"
restart_limit = 0
timeout = 2000
tls_skip_verify = false

[[services.script_checks]]
command = "/app/health_checks/health_check.sh"
args = []
grace_period = "1s"
interval = "5s"
restart_limit = 0
timeout = "1s"

[processes]
app = "node index.js"
